# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- development

variables:
  image_name: openjdk
  image_tag: 17-jdk-slim
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

stages:
- stage: Build
  displayName: 'Build NetFramework'

  jobs:
  - job: Build
    displayName: 'Build NetFramework'
    pool:
      vmImage: 'windows-latest'
    steps:
    - task: NuGetToolInstaller@1
      displayName: 'Use NuGet 5 3 1'

    - task: NuGetCommand@2
      inputs:
        restoreSolution: '$(solution)'
  
    - task: SonarCloudPrepare@1
      inputs:
        SonarCloud: 'SonarCloud_Sc'
        organization: 'fcmbdiglabrepo'
        scannerMode: 'MSBuild'
        projectKey: 'FCMBDigLabRepo_Capritech-Semanix-v2Legacy-Revamp'
        projectName: 'Capritech-Semanix v2(Legacy Revamp)'
    - task: VSBuild@1
      continueOnError: true
      inputs:
        solution: '$(solution)'
        msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(build.artifactStagingDirectory)\WebApp.zip" /p:DeployIisAppPath="Default Web Site"'
        platform: '$(buildPlatform)'
        configuration: '$(buildConfiguration)'
    
    - task: VSTest@2
      continueOnError: true
      inputs:
        platform: '$(buildPlatform)'
        configuration: '$(buildConfiguration)'
    - task: SonarCloudAnalyze@1
    - task: SonarCloudPublish@1
      continueOnError: false
      inputs:
        pollingTimeoutSec: '300'
    - task: PublishBuildArtifacts@1
      continueOnError: true
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'
