apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: capritech-Semanix-v2-legacy-revamp-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: capritech-Semanix-v2-legacy-revamp
  minReplicas: 1
  maxReplicas: 2
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 70
